create table if not exists public.users (
  user_id bigint primary key,
  language text,
  first_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.group_settings (
  chat_id bigint primary key,
  language text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id bigint not null,
  term_id text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, term_id)
);

create table if not exists public.history (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  term_id text not null,
  viewed_at timestamptz not null default now()
);

create index if not exists idx_history_user on public.history (user_id, viewed_at desc);

create table if not exists public.streaks (
  user_id bigint primary key,
  last_daily_date date,
  streak_count integer not null default 0,
  max_streak integer not null default 0,
  streak_freezes_used integer not null default 0,
  freeze_reset_date date,
  timezone text not null default 'America/Sao_Paulo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.scheduled_notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  scheduled_at timestamptz not null,
  sent_at timestamptz,
  type text not null
);

create index if not exists idx_notifications_scheduled on public.scheduled_notifications (scheduled_at, sent_at);

create table if not exists public.quiz_sessions (
  user_id bigint primary key,
  term_id text not null,
  correct_idx integer not null,
  session_data jsonb not null
);

create table if not exists public.user_daily_activity (
  user_id bigint not null,
  date date not null,
  primary key (user_id, date)
);

create table if not exists public.user_path_progress (
  user_id bigint not null,
  path_id text not null,
  step integer not null default 0,
  completed boolean not null default false,
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, path_id)
);

create table if not exists public.group_members (
  chat_id bigint not null,
  user_id bigint not null,
  last_seen timestamptz not null default now(),
  primary key (chat_id, user_id)
);

create table if not exists public.group_streaks (
  chat_id bigint primary key,
  current_streak integer not null default 0,
  max_streak integer not null default 0,
  last_active_date date,
  last_broken_announcement_date date,
  updated_at timestamptz not null default now()
);

create table if not exists public.group_daily_participants (
  chat_id bigint not null,
  user_id bigint not null,
  date date not null,
  primary key (chat_id, user_id, date)
);

alter table public.users disable row level security;
alter table public.group_settings disable row level security;
alter table public.favorites disable row level security;
alter table public.history disable row level security;
alter table public.streaks disable row level security;
alter table public.scheduled_notifications disable row level security;
alter table public.quiz_sessions disable row level security;
alter table public.user_daily_activity disable row level security;
alter table public.user_path_progress disable row level security;
alter table public.group_members disable row level security;
alter table public.group_streaks disable row level security;
alter table public.group_daily_participants disable row level security;
