[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]
dependsOn = ["install"]

[start]
cmd = "node dist/server.js"
dependsOn = ["build"]
