import * as vscode from "vscode";

import { GlossaryOSClient } from "../api/glossary-os-client";
import { detectLocale } from "../utils/locale-detector";

const GENERATE_COMMENT_PATTERN = /\/\/\s*@generate:\s*(.+)$/m;

function findGenerateRequest(document: vscode.TextDocument, preferredLine: number) {
  const lineMatch = GENERATE_COMMENT_PATTERN.exec(document.lineAt(preferredLine).text);
  if (lineMatch) {
    return {
      request: lineMatch[1].trim(),
      line: preferredLine,
    };
  }

  for (let index = 0; index < document.lineCount; index += 1) {
    const match = GENERATE_COMMENT_PATTERN.exec(document.lineAt(index).text);
    if (match) {
      return {
        request: match[1].trim(),
        line: index,
      };
    }
  }

  return null;
}

export async function generateFromCommentCommand(): Promise<void> {
  const editor = vscode.window.activeTextEditor;
  if (!editor) return;

  const document = editor.document;
  const found = findGenerateRequest(document, editor.selection.active.line);

  if (!found) {
    void vscode.window.showWarningMessage(
      'No @generate comment found. Add "// @generate: your request here" and run again.',
    );
    return;
  }

  const request = found.request;
  const client = new GlossaryOSClient();
  const result = await client.generateCode({
    request,
    locale: detectLocale(),
  });

  const insertText = result.extractedCode
    ? `\n// Generated by Solana Glossary Copilot\n${result.extractedCode}\n`
    : `\n// Glossary Copilot could not extract a code block.\n// ${result.explanation.replace(/\n/g, "\n// ")}\n`;

  const line = found.line + 1;
  const edit = new vscode.WorkspaceEdit();
  edit.insert(document.uri, new vscode.Position(line, 0), insertText);
  await vscode.workspace.applyEdit(edit);

  const notes = vscode.window.createOutputChannel("Solana Glossary Copilot");
  notes.clear();
  notes.appendLine("Generated by Solana Glossary Copilot");
  notes.appendLine("");
  notes.appendLine(result.explanation);
  notes.appendLine("");
  notes.appendLine("Key concepts:");
  for (const concept of result.keyConcepts) {
    notes.appendLine(`- ${concept.label}: ${concept.reason}`);
  }
  notes.show(true);

  void vscode.window.showInformationMessage("Generation inserted below the current line.");
}
